version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  fpm:
    build:
      dockerfile: Dockerfile.fpm
      context: .
    ports:
      - 9000:9000
    volumes:
      - .:/app
